// react/src/components/pkFilter.jsx
import React, { useState, useEffect } from "react";
import { Button } from "react-bootstrap";

const PkFilter = (props) => {
  const { list, filterlist } = props;
  //const [list, setList] = useState([]);
  //const [filterItems, setFilterItems] = useState([]);
  // useEffect(() => {
  //     debugger;
  //     setList(props.list)
  //     console.log(props.list, list)

  // }, [])

  const handlefilterlist = (index, requestUrl) => {
    list[index].selected = !list[index].selected;
    let filterItems = list.filter((item, index) => {
      return item.selected;
    });
    filterlist(filterItems);
  };

  return (
    <div className="filter-container">
      <div>Types:</div>
      <div>
        {list.map((item, index) => {
          return (
            <Button
              variant={item.selected ? "primary" : "light"}
              key={index}
              onClick={() => {
                handlefilterlist(index, item.url);
              }}
            >
              {item.name}
            </Button>
          );
        })}
      </div>
    </div>
  );
};

export default PkFilter;

// vue/src/components/pkFilter.vue
<template>
  <div class="filter-container">
    <div>Types:</div>
    <div>
      <el-button v-for="(item, index) in list" :type="item.selected?'primary':''" :key="index"
        @click="handlefilterlist(index, item.url)">{{item.name}}
      </el-button>
    </div>
  </div>




</template>

<script>
export default {
  name: 'pkFilter',
  data() {
    return {

    }
  },
  mounted() {

  },
  methods: {
    handlefilterlist(index, requestUrl) {
      this.list[index].selected = !this.list[index].selected;
      this.filterItems = this.list.filter((item, index) => {
        return item.selected
      })
      this.filterlist(this.filterItems);
      this.$forceUpdate()
    }
  },
  props: ['list', 'filterlist']
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.filter-container {
  display: flex;
}

.filter-container div:nth-of-type(1) {
  align-self: flex-start;
  margin: 1rem;
}

button {
  margin: 0.5rem;
}
</style>
